model:
  type: "LatentSDE"
  latent_dim: &latentdim 32
  context_dim: 32

  obs_encoder:
    type: "Recurrent_Encoder"
    hidden_size: 32

  SDE:
    drift:
      type: "MLP"
      hidden_size: 16
      depth: 2
      activation: swish
    drift_aug:
      type: "MLP"
      hidden_size: 16
      depth: 2
      activation: swish
    diffusion:
      type: "SparseMLP"
      activation: sigmoid
    solver: LambaEM()
    kwargs:
        dt: 0.5

  obs_decoder:
    type: "BranchDecoder"
    hidden_size: 32
    depth: 2
    dists: ["Classification", "Poisson"]


training:
  learning_rate: 0.005
  optimizer: AdamW(0.005) 
  epochs: 200
  log_freq: 20
  viz_freq: 1
  stop_patience: 20
  lr_decay:
    type: "exponential"
    gamma: 0.9  # Decay factor per epoch (0.95 means 95% of previous value)
    step_every: 50  # Apply decay every epoch
  validation:
      latent_dim: *latentdim  
      solver: LambaEM()
      mcmc_samples: 50
      kwargs:
          dt: 0.5
experiment:
  name: "LatentSDE_PKPD_V0"
  description: "First experiment with a Latent SDE model using Rhythm on the PKPD model"
  path: "experiments/" 
