model:
  type: "LatentSDE"
  context_dim: 0

  SDE:
    drift:
      type: "MLP"
      hidden_size: 64
      depth: 1
      activation: swish
    drift_aug:
      type: "MLP"
      hidden_size: 64
      depth: 1
      activation: swish
    diffusion:
      type: "DiffusionMLP"
      hidden_size: 32
      depth: 1
      activation: swish
    solver: EM()
    kwargs:
      dt: 0.02

  validation:
    solver: EM()
    kwargs:
      dt: 0.02

experiment:
  name: "LatentSDE_PKPD_NoContext"
  description: "Ablation: Latent SDE without encoder context"
  path: "experiments/"
