model:
  type: "LatentODE"

  ODE:
    vector_field:
      type: "MLP"
      hidden_size: 64
      depth: 1
      activation: swish
    solver: Euler()
    kwargs:
      dt: 0.01

  validation:
    solver: Euler()
    kwargs:
      dt: 0.01

experiment:
  name: "LatentODE_PKPD_V0"
  description: "Latent ODE model for PKPD forecasting"
  path: "experiments/"
