model:
  type: "LatentSDE"

  SDE:
    drift:
      type: "MLP"
      hidden_size: 64
      depth: 1
      activation: swish
    drift_aug:
      type: "MLP"
      hidden_size: 64
      depth: 1
      activation: swish
    diffusion:
      type: "DiffusionMLP"
      hidden_size: 32
      depth: 1
      activation: swish
    solver: EM()
    kwargs:
      dt: 0.01

  validation:
    solver: EM()
    kwargs:
      dt: 0.02

experiment:
  name: "LatentSDE_PKPD_V0"
  description: "Latent SDE model for PKPD forecasting"
  path: "experiments/"
