model:
  encoder: 
    hidden_size: 32
    num_layers: 4
  output_head:
    hidden_size: 32
    num_layers: 4


training:
  learning_rate: 0.005
  optimizer: AdamW(0.005) 
  epochs: 200
  log_freq: 20
  viz_freq: 10
  stop_patience: 20
  lr_decay:
    type: "exponential"
    gamma: 0.9  # Decay factor per epoch (0.95 means 95% of previous value)
    step_every: 50  # Apply decay every epoch
  validation:


experiment:
  name: "RNN_PKPD_Forecasting_V0"
  description: "First experiment with a RNN model using Rhythm on the PKPD dataset"
  path: "experiments/"
