model:
  type: "LatentCDE"
  latent_dim: &latentdim 32
  covars_dim: 2

  obs_encoder:
    type: "Recurrent_Encoder"
    hidden_size: 32

  CDE:
    vector_field:
      type: "CDEField"
      hidden_size: 32
      depth: 1
      activation: swish
    solver: Tsit5()
    kwargs:
        dt: 0.1

  obs_decoder:
    type: "MultiHeadLinearDecoder"
    dists: ["Gaussian"]

training:
  learning_rate: 0.002
  optimizer: AdamW(0.002)
  epochs: 10
  log_freq: 1
  viz_freq: 10
  stop_patience: 10
  lr_decay:
    type: "exponential"
    gamma: 0.9
    step_every: 50
  validation:
      latent_dim: *latentdim
      solver: Tsit5()
      mcmc_samples: 50
      kwargs:
          dt: 0.1

experiment:
  name: "LatentCDE_Glucose_V0"
  description: "Latent CDE model for Bergman glucose forecasting"
  path: "experiments/"
