model:
  type: "LatentODE"
  context_dim: 16 
  ODE:
    vector_field:
      type: "MLP"
      hidden_size: 16
      depth: 1
      activation: swish
    solver: Euler()
    kwargs:
      dt: 0.02

  validation:
    solver: Euler()
    kwargs:
      dt: 0.02

experiment:
  name: "LatentODE_Glucose_V0"
  description: "Latent ODE model for Bergman glucose forecasting"
  path: "experiments/"
