model:
  type: "LatentSDE"
  latent_dim: &latentdim 32 
  context_dim: 32

  obs_encoder:
    type: "Recurrent_Encoder"
    hidden_size: 32

  SDE:
    drift:
      type: "MLP"
      hidden_size: 32
      depth: 1
      activation: swish
    drift_aug:
      type: "MLP"
      hidden_size: 32
      depth: 1
      activation: swish
    diffusion:
      type: "SparseMLP"
      activation: sigmoid
    solver: EM()
    kwargs:
        dt: 0.01

  obs_decoder:
    type: "MultiHeadLinearDecoder"
    dists: ["Gaussian"]

training:
  learning_rate: 0.002
  optimizer: AdamW(0.002)
  epochs: 200
  log_freq: 10
  viz_freq: 10
  stop_patience: 20
  lr_decay:
    type: "exponential"
    gamma: 0.9
    step_every: 50
  validation:
      latent_dim: *latentdim
      solver: EM()
      mcmc_samples: 50
      kwargs:
          dt: 0.01

experiment:
  name: "LatentSDE_Glucose_V0"
  description: "Latent SDE model for Bergman glucose forecasting"
  path: "experiments/"
