model:
  type: "LatentLSTM"
  context_dim: 32

  dynamics:
    type: "LSTM"
    hidden_size: 32
    depth: 1

  validation:
    solver: Tsit5()
    kwargs:
      dt: 0.1

experiment:
  name: "LatentLSTM_Glucose_V0"
  description: "Latent LSTM model for Bergman glucose forecasting"
  path: "experiments/"
