model:
  type: "LatentCDE"

  CDE:
    vector_field:
      type: "CDEField"
      hidden_size: 64
      depth: 1
      activation: swish
    solver: Euler()
    kwargs:
      dt: 0.02

  validation:
    solver: Euler()
    kwargs:
      dt: 0.02

experiment:
  name: "LatentCDE_ICU_V0"
  description: "Latent CDE model for ICU forecasting"
  path: "experiments/"
