model:
  encoder: 
    hidden_size: 8
    latent_dim: 32
    num_layers: 2
  output_head:
    hidden_size: 32
    num_layers: 1


training:
  learning_rate: 0.005
  optimizer: AdamW(0.005) 
  epochs: 100
  log_freq: 10
  viz_freq: 10
  stop_patience: 20
  lr_decay:
    type: "exponential"
    gamma: 0.9  # Decay factor per epoch (0.95 means 95% of previous value)
    step_every: 50  # Apply decay every epoch
  validation:
    mcmc_samples: 50


experiment:
  name: "latent lstm ICU forecasting V0"
  description: "First experiment with a latent LSTM model using Rhythm on the ICU dataset"
  path: "experiments/"
