model:
  type: "LatentLSTM"

  dynamics:
    type: "LSTM"
    hidden_size: 32
    depth: 1

  validation:
    solver: Tsit5()
    kwargs:
      dt: 0.01

experiment:
  name: "LatentLSTM_ICU_V0"
  description: "Latent LSTM model for ICU forecasting"
  path: "experiments/"
