model:
  type: "LatentSDE"
  latent_dim: &latentdim 8
  context_dim: 8

  obs_encoder:
    type: "Recurrent_Encoder"
    hidden_size: 8

  SDE:
    drift:
      type: "MLP"
      hidden_size: 8
      depth: 0
      activation: swish
    drift_aug:
      type: "MLP"
      hidden_size: 8
      depth: 0
      activation: swish
    diffusion:
      type: "SparseMLP"
      activation: sigmoid
    solver: EM()
    kwargs:
        dt: 0.01

  obs_decoder:
    type: "MultiOutputDecoder"
    hidden_size: 64
    depth: 0
    dist: 
    - "None"
    - "None"


training:
  learning_rate: 0.005
  optimizer: AdamW(0.005)
  epochs: 100
  log_freq: 10
  viz_freq: 50
  stop_patience: 5
  lrdecay_patience: 5
  validation:
      latent_dim: *latentdim  
      solver: EM()
      mcmc_samples: 10
      kwargs:
          dt: 0.01

experiment:
  name: "LatentSDE_PKPD_V0"
  description: "First experiment with a Latent SDE model using Rhythm on the PKPD model"
  path: "experiments/" 
