model:
  type: "LatentSDE"
  latent_dim: 8
  context_dim: 32

  obs_encoder:
    type: "Recurrent_Encoder"
    hidden_size: 64

  SDE:
    drift:
      type: "MLP"
      hidden_size: 64
      depth: 0
      activation: tanh
    drift_aug:
      type: "MLP"
      hidden_size: 64
      depth: 0
      activation: tanh
    diffusion:
      type: "SparseMLP"
      activation: sigmoid
    solver: EM()
    kwargs:
      dt: 1.0

  obs_decoder:
    type: "MLP_Decoder"
    hidden_size: 64
    depth: 0
    dist: "Poisson"


training:
  learning_rate: 0.001
  optimizer: AdamW(1e-3)
  epochs: 500
  log_freq: 5
  viz_freq: 100
  stop_patience: 5
  lrdecay_patience: 3
  validation:
      solver: EM()
      mcmc_samples: 100
      kwargs:
          dt: 1.0

experiment:
  name: "LatentSDE_PKPD_V0"
  description: "First experiment with a Latent SDE model using Rhythm on the PKPD model"
  path: "experiments/" 
