model:
  type: "LatentSDE"
  latent_dim: 10
  context_dim: 10
  obs_encoder:
    type: "Recurrent_Encoder"
    hidden_size: 64
  SDE:
    drift:
      type: "MLP"
      hidden_size: 128
      depth: 0
      activation: tanh
    drift_aug:
      type: "MLP"
      hidden_size: 64
      depth: 0
      activation: softplus
    diffusion:
      type: "SparseMLP"
      activation: sigmoid
    solver: "EM"
  obs_decoder:
    type: "MLP_Decoder"
    hidden_size: 128
    depth: 0
    dist: "Poisson"


training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 100
  optimizer: AdamW(1e-3)
  log_freq: 10
  viz_freq: 10
  save_path: "results/"
  stop_patience: 50
  lrdecay_patience: 20
  n_samples: 10
  kwargs:
    saveat: 0.1
    dt: 0.1f0
