model:
  type: "LatentSDE"
  latent_dim: &latentdim 32
  context_dim: 32

  obs_encoder:
    type: "Recurrent_Encoder"
    hidden_size: 32

  SDE:
    drift:
      type: "MLP"
      hidden_size: 32
      depth: 1
      activation: swish
    drift_aug:
      type: "MLP"
      hidden_size: 32
      depth: 1
      activation: swish
    diffusion:
      type: "SparseMLP_ODE"
      activation: sigmoid
    solver: EM()
    kwargs:
        dt: 0.01

  obs_decoder:
    type: "BranchDecoder"
    hidden_size: 32
    depth: 1
    dists: 
    - "None"
    - "None"


training:
  learning_rate: 0.005
  optimizer: AdamW(0.005)
  epochs: 500
  log_freq: 50
  viz_freq: 10
  stop_patience: 10
  lrdecay_patience: 5
  validation:
      latent_dim: *latentdim  
      solver: EM()
      mcmc_samples: 50
      kwargs:
          dt: 0.01

experiment:
  name: "LatentSDE_PKPD_V0"
  description: "First experiment with a Latent SDE model using Rhythm on the PKPD model"
  path: "experiments/" 
