model:
  type: "RNN"
  latent_dim: &latentdim 8

  obs_encoder:
    type: "Recurrent_Encoder"
    hidden_size: 64

  obs_decoder:
    type: "BranchDecoder"
    hidden_size: 64
    depth: 1
    dists: ["Gaussian", "Gaussian", "Gaussian", "Gaussian","Gaussian","Gaussian","Gaussian" ]


training:
  learning_rate: 0.005
  optimizer: AdamW(0.001)
  epochs: 2000
  log_freq: 10
  viz_freq: 100
  stop_patience: 10
  lrdecay_patience: 5
  validation:
      latent_dim: *latentdim  
      mcmc_samples: 50
      kwargs:
          dt: 0.01

experiment:
  name: "LatentSDE_ICU_Sys_ID_V0"
  description: "First experiment with a Latent SDE model using Rhythm on the ICU dataset"
  path: "experiments/" 
